AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  codedeploy-slack

  Sample SAM Template for codedeploy-slack

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CodeDeploySlackFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: codedeploy-slack/
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Events:
        CodeDeploySlack:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /notify
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for CodeDeploy Slack function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/notify/"
  CodeDeploySlackFunction:
    Description: "CodeDeploy Slack Lambda Function ARN"
    Value: !GetAtt CodeDeploySlackFunction.Arn
  CodeDeploySlackFunctionIamRole:
    Description: "Implicit IAM Role created for CodeDeploy Slack function"
    Value: !GetAtt CodeDeploySlackFunctionRole.Arn
